In [1]:
from util import *
from neuralnet import *

In [2]:
train_dataset, val_dataset, test_dataset = load_data('./data/')

In [3]:
train_dataset.X.shape, val_dataset.X.shape, test_dataset.X.shape

((40000, 3073), (10000, 3073), (10000, 3073))

In [198]:
train_dataset.X[:,:-1].reshape((-1, 3, IMAGE_SIZE * IMAGE_SIZE))[:, 0, :].std() # should be 1

1.0000000000000013

In [10]:
train_dataset.X[42].mean(), train_dataset.X[42].std()

(0.22134858079888198, 0.901623064354778)

In [199]:
train_dataset.X.shape[0] / val_dataset.X.shape[0] # should be 4 assuming 0.2 val proportion

4.0

In [200]:
train_dataset.t.shape

(40000, 10)

In [201]:
from constants import configYamlPath
from configuration import load_config

c = load_config(f"{configYamlPath}/config_2c.yaml")

In [202]:
c

Config(layer_specs=[3072, 128, 256, 10], activation='tanh', learning_rate=0.01, batch_size=64, epochs=100, early_stop=True, early_stop_epoch=5, regularization_type='L2', regularization_lambda=0.01, momentum=True, momentum_gamma=0.9, weight_type='random')

In [203]:
gm = generate_minibatches(train_dataset, 64)
next(gm).X.shape

(64, 3073)

In [204]:
model = Neuralnetwork(c)

In [205]:
model

[Layer 0: 3072 -> 128 (tanh), Layer 1: 128 -> 256 (tanh), Layer 2: 256 -> 10 (output)]

In [206]:
batch = next(gm)
model.forward(batch.X, batch.t)

(64, 3073)
(64, 129)
(64, 257)


(array([[0.0985364 , 0.10320475, 0.09987519, 0.10064841, 0.10172169,
         0.10407718, 0.09420625, 0.09983779, 0.09928047, 0.09861187],
        [0.10211749, 0.09725643, 0.09925212, 0.09849599, 0.09812049,
         0.09562591, 0.10568763, 0.09973551, 0.10137081, 0.10233764],
        [0.10212119, 0.09724971, 0.09925108, 0.09849373, 0.09811628,
         0.09561685, 0.10570101, 0.0997353 , 0.101373  , 0.10234185],
        [0.10212136, 0.0972494 , 0.09925104, 0.09849362, 0.0981161 ,
         0.09561644, 0.1057016 , 0.0997353 , 0.1013731 , 0.10234204],
        [0.10212096, 0.09725012, 0.09925115, 0.09849388, 0.09811654,
         0.09561741, 0.10570017, 0.09973531, 0.10137286, 0.10234158],
        [0.10180711, 0.0978171 , 0.09933719, 0.09868512, 0.09846432,
         0.09637405, 0.10458782, 0.09974702, 0.10119484, 0.10198543],
        [0.09848124, 0.10330055, 0.09988427, 0.10067659, 0.10177646,
         0.1042117 , 0.09403754, 0.09983368, 0.09924668, 0.0985513 ],
        [0.10212136, 0.0972

In [207]:
train_dataset.X[:10]

array([[-0.05166751, -0.00404233,  0.15470827, ...,  0.03217787,
         0.16711652,  1.        ],
       [ 0.99608642,  0.99608642,  1.01196147, ..., -0.79244722,
        -0.83742677,  1.        ],
       [ 1.02783653,  0.99608642,  0.99608642, ...,  0.04717105,
         0.15212334,  1.        ],
       ...,
       [ 0.39283416,  0.39283416,  0.40870922, ..., -0.49258355,
        -0.447604  ,  1.        ],
       [-0.24216822, -0.30566846, -0.19454304, ..., -0.65750857,
        -0.43261082,  1.        ],
       [-0.25804328, -0.32154352, -0.1310428 , ..., -0.95737224,
        -1.06232453,  1.        ]])

In [208]:
x_ = train_dataset.X[:10]
x_

array([[-0.05166751, -0.00404233,  0.15470827, ...,  0.03217787,
         0.16711652,  1.        ],
       [ 0.99608642,  0.99608642,  1.01196147, ..., -0.79244722,
        -0.83742677,  1.        ],
       [ 1.02783653,  0.99608642,  0.99608642, ...,  0.04717105,
         0.15212334,  1.        ],
       ...,
       [ 0.39283416,  0.39283416,  0.40870922, ..., -0.49258355,
        -0.447604  ,  1.        ],
       [-0.24216822, -0.30566846, -0.19454304, ..., -0.65750857,
        -0.43261082,  1.        ],
       [-0.25804328, -0.32154352, -0.1310428 , ..., -0.95737224,
        -1.06232453,  1.        ]])

In [215]:
for a in ["sigmoid", "tanh", "ReLU", "output"]:
    act = Activation(a)
    print("----")
    display(act.forward(x_).shape)
    display(act.backward(x_).shape)

----


(10, 3073)

(10, 3073)

----


(10, 3073)

(10, 3073)

----


(10, 3073)

(10, 3073)

----


(10, 3073)

(10, 3073)

In [225]:
from train import train

train(model, train_dataset, val_dataset, c)

  0%|          | 0/100 [00:04<?, ?it/s]

Unexpected exception formatting exception. Falling back to standard exception



Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/cse-151b/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/_5/3wr8xblj56dd_xpscf0zt6t00000gn/T/ipykernel_73250/3093267326.py", line 3, in <cell line: 3>
    train(model, train_dataset, val_dataset, c)
  File "/Users/xiyan/Developer/cse-151b-pa2-xys_yxc_zlw/train.py", line 34, in train
    train_result = sgd(model, train_dataset, config)
  File "/Users/xiyan/Developer/cse-151b-pa2-xys_yxc_zlw/train.py", line 66, in sgd
    _, forward_res = model.forward(batch.X, batch.t)
  File "/Users/xiyan/Developer/cse-151b-pa2-xys_yxc_zlw/neuralnet.py", line 253, in forward
    output = reduce(lambda fst, snd: append_bias(snd(fst)), self.layers, x)[:, :-1]
  File "/Users/xiyan/Developer/cse-151b-pa2-xys_yxc_zlw/neuralnet.py", line 253, in <lambda>
    output = reduce(lambda fst, snd: append_bias(snd(fst)), 

In [220]:
r = Regularization("L1", 0.01)

In [224]:
# r.forward(np.array([1, 2, 3]))
r.backward(np.array([1, 2, 3]))

array([0.01, 0.01, 0.01])